### ISSUE TITLE
cannot install unoconv in centos 6.5

### ISSUE THREAD

**Issue by arundaskd** [repoforge/rpms#319]
When I try to install unoconv I get an error message like

error: Failed dependencies:
        openoffice.org-pyuno >= 2.0 is needed by unoconv-0.5-1.el6.rf.noarch

I installed libreoffice, as there were no packages available for openoffice.

Thank you

**Comment by ankitvadariya** [comment]
100% Working solution is here.
1) Download the latest rpmforge-release rpm from
      http://apt.sw.be/redhat/el6/en/i386/rpmforge/RPMS/
(I had download http://apt.sw.be/redhat/el6/en/i386/rpmforge/RPMS/rpmforge-release-0.5.3-1.el6.rf.i686.rpm )

2) Install rpmforge-release rpm:
      rpm -Uvh rpmforge-release*rpm

3) Install unoconv rpm package:
      yum install unoconv
