### ISSUE TITLE
Unable to resolve host address

### ISSUE THREAD

**Issue by ylupien** [repoforge/rpms#373]
Unable to install RPM Forge. 

[root@srv ~]# wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
--2016-05-12 16:46:57--  http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
Resolving pkgs.repoforge.org (pkgs.repoforge.org)... 78.46.17.228
Connecting to pkgs.repoforge.org (pkgs.repoforge.org)|78.46.17.228|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://rpmforge.sw.be/redhat/el6/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm [following]
--2016-05-12 16:46:58--  http://rpmforge.sw.be/redhat/el6/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
Resolving rpmforge.sw.be (rpmforge.sw.be)... failed: Name or service not known.
**wget: unable to resolve host address ‘rpmforge.sw.be’**

**Comment by gsverma** [comment]
have the exact same issue with CentOS 7.
