### ISSUE TITLE
This this site just go down?  wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm 

### ISSUE THREAD

**Issue by hectoralicea** [repoforge/rpms#376]
just stopped working today.  What's the alternative?  Running CentOS 6.

**Comment by davidhrbac** [comment]
duplicate #375

**Comment by davidhrbac** [comment]
@hectoralicea you can grab it here http://repository.it4i.cz/mirrors/repoforge/redhat/el6/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
