### ISSUE TITLE
http://mirror-status.repoforge.org/ is down

### ISSUE THREAD

**Issue by Trefex** [repoforge/rpms#379]
Hi,

The http://mirror-status.repoforge.org/ seems to be down, making all our VMs fail on checking for updates.

Thanks for any feedback on this.

**Comment by davidhrbac** [comment]
@Trefex vm seems to be down. I can reset it tomorrow.

**Comment by Trefex** [comment]
Thanks @davidhrbac

**Comment by davidhrbac** [comment]
@Trefex up and running. Thanks for letting me know.
